alias ls='ls --color=auto'
alias l='ls'
alias ll='ls -ahlF'
alias la='ls -a'
alias cd\.\.='cd ..;'
alias \.\.='cd ..;'
alias drdesktop='pushd ~/Desktop;'
alias powertop='sudo powertop;'
alias axel='axel -an9'
alias iotop='sudo iotop;'
alias sync='sudo sync;'
alias writeinclipboard='[[ -x `which xclip 2>/dev/null` ]] && cat << EOF | xclip -selection clipboard '
alias dc='docker-compose'
alias dm='docker-machine'
alias dme='dmenv'
alias dmu='dmenv -u'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dimg='docker images'
alias khra='sudo !!;'
alias youtube-dlaudio='youtube-dl -x --audio-format=mp3 '
