alias ls='ls --color=auto'
alias ll='ls -ahlF'
alias la='ls -a'
alias cd\.\.='cd ..'
alias \.\.='cd ..'
alias drdesktop='pushd ~/Desktop'
alias powertop='sudo powertop'
alias axel='axel -an9'
alias iotop='sudo iotop'
alias writeinclipboard='[[ -x `which xclip 2>/dev/null` ]] && cat << EOF | xclip -selection clipboard '
alias dm='docker-machine'
alias dc='docker-compose'
